language: objective-c
osx_image: xcode9
notifications:
  email: false
branches:
  only: 
    - master  
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=VersionTracker.xcworkspace
  - FRAMEWORK_SCHEME="VersionTracker"
  - EXAMPLE_SCHEME="iOS Example"
  matrix:
    # - DESTINATION="OS=3.2,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME"  RUN_TESTS="NO"  BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SCHEME="$FRAMEWORK_SCHEME"  RUN_TESTS="NO"  BUILD_EXAMPLE="NO"  POD_LINT="NO"

    - DESTINATION="OS=11.0,name=iPhone 7 Plus"     SCHEME="$FRAMEWORK_SCHEME"  RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$FRAMEWORK_SCHEME"  RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"

    - DESTINATION="OS=11.0,name=Apple TV 1080p"    SCHEME="$FRAMEWORK_SCHEME"  RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"     SCHEME="$FRAMEWORK_SCHEME"  RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"

    - DESTINATION="arch=x86_64"                    SCHEME="$FRAMEWORK_SCHEME"  RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

after_success:
   - sleep 5 # Workaround for https://github.com/travis-ci/travis-ci/issues/4725    